Repository codestates/BTA1stProject-20, pull requests merged in 2022-10, with the labels that each got.

#10 mui로 theme, page mocking
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.tsx
  src/components/.gitkeep
  src/contexts/ColorModeContext.ts
  src/contexts/index.ts
  src/index.css
  src/layouts/DefaultLayout.tsx
  src/layouts/index.ts
  src/logo.svg
  src/pages/.gitkeep
  src/pages/Main.tsx
  src/pages/Page1.tsx
  src/pages/Page2.tsx
  src/pages/index.ts
Labels: 🎨UI

#12 meta: project 구조 변경
  .gitignore
  client/.editorconfig
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/imx_icon_128.png
  client/public/imx_icon_16.png
  client/public/imx_icon_192.png
  client/public/imx_icon_32.png
  client/public/imx_icon_334.png
  client/public/imx_icon_48.png
  client/public/index.html
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/components/.gitkeep
  client/src/contexts/ColorModeContext.ts
  client/src/contexts/index.ts
  client/src/index.css
  client/src/index.tsx
  client/src/layouts/DefaultLayout.tsx
  client/src/layouts/index.ts
  client/src/pages/.gitkeep
  client/src/pages/Main.tsx
  client/src/pages/Page1.tsx
  client/src/pages/Page2.tsx
  client/src/pages/index.ts
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/setupTests.ts
  client/tsconfig.json
Labels: 🤝 Project

#18 feat: transfer API 수정
  server/docs/wallet/wallet.transfer.yaml
  server/src/controller/walletController.ts
  server/src/service/walletService.ts
  server/src/utility/BlockchainUtil.ts
  server/src/utility/apiResponse.ts
Labels: 🔥 feature

#21 feat: login API 추가
  server/docs/path.yaml
  server/docs/wallet/wallet.login.yaml
  server/src/controller/walletController.ts
  server/src/route/api.ts
  server/src/service/walletService.ts
Labels: 🔥 feature

#22 api 연동
  client/src/components/CoinCard/CoinCard.tsx
  client/src/constants/endpoints.ts
  client/src/constants/strings.ts
  client/src/hooks/index.ts
  client/src/hooks/useBalance.ts
  client/src/pages/BringWallet.tsx
  client/src/pages/CreateWallet.tsx
  client/src/pages/SeedCheck.tsx
  client/src/pages/SeedReveal.tsx
  client/src/pages/Send.tsx
  client/src/pages/SendConfirm.tsx
  client/src/pages/SendInput.tsx
  client/src/pages/Start.tsx
  client/src/pages/Wallet.tsx
  client/src/pages/WelcomeBack.tsx
  client/src/states/atoms.ts
  client/src/states/index.ts
Labels: 🔥 feature
